version: '3.0'

services:
    colin_mongo_database:
        image: mongo:4.0
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        volumes:
            - /mnt1/colinzuo:/mnt1/colinzuo
            - /home/colinzuo:/home/colinzuo
        network_mode: "host"
        restart: always
        command: mongod
     
    colin_mongo_express:
        image: mongo-express
        ports:
          - 8081:8081
        environment:
          - ME_CONFIG_MONGODB_ADMINUSERNAME=root
          - ME_CONFIG_MONGODB_ADMINPASSWORD=example
          - ME_CONFIG_MONGODB_SERVER=localhost
        network_mode: "host"
        restart: always